### ISSUE TITLE
Using UUID as primary key

### ISSUE THREAD

**Issue by acidjunk** [accent-starlette/starlette-auth#2]
Thanks for this auth stuff. Would it be possible to support UUID as primary key somehow? I already fiddled around a bit with it in my fork but could't get it to work without setting stuff to postgres dialect.

Probably nicest way would be a config option in starlette-auth

**Comment by stuartaccent** [comment]
Hi @acidjunk,

That sounds like a better idea than an int field, tbh its really early days for these repos and have no idea where they are heading atm. We are only on our second site using starlette and know we need a bunch of generic stuff. Let me give it some thought as I may just change it permanently.

Where we will eventually end up is a bunch of repos that act independently centred around the core repo that come together to form either a basic site or a full blown cms. At least thats the plan I think. I don't think they will ever live on pypi in my opinion so i dont mind changes just dont want to be fixing every site the more we change :D

If you have ideas feel free to shout. 

Cheers, Stu

**Comment by acidjunk** [comment]
Nice :)

Let me know if I can help: docs seem a bit empty, and I don't mind writing them (is this the right time to add some docs: or do you think it's too early for that?)

**Comment by stuartaccent** [comment]
Hi @acidjunk 

Thanks for the offer, we currently have a new dev here writing these docs as we speak to get to grips with things. @davidaccent is the man in question. Will have a chat and come back to you.

Hes currently working through:

- https://github.com/accent-starlette/starlette-admin
- https://github.com/accent-starlette/starlette-auth
- https://github.com/accent-starlette/starlette-audit
- https://github.com/accent-starlette/starlette-core
- https://github.com/accent-starlette/starlette-files
